on: [push, pull_request]
name: CI ktlint
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: |
          ls -lah
          git log -n 4
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.29.0/ktlint && chmod a+x ktlint
      - name: Check for coding convention issues
        run: './ktlint "app/src/*/.kt"'
